describe('Buy Page', () => {
    it('successfully login and buy', () => {
      cy.login()
      cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
      cy.get('.shopping_cart_badge').click()
      cy.get('[data-test="checkout"]').click()
      cy.get('[data-test="firstName"]').type('Juan')
      cy.get('[data-test="lastName"]').type('Diaz,Alguera')
      cy.get('[data-test="postalCode"]').type('1251')
      cy.get('[data-test="continue"]').click()
      cy.get('[data-test="finish"]').click()
     cy.wait(500)
     cy.scrollTo(100, 150)
     //cy.wait(1500)
     //cy.get('[data-test="back-to-products"]').click()
    })
  })