describe('Buy Page', () => {
    it('successfully login and buy', () => {
      cy.login()
      cy.buybackpack()
      cy.ShoppingCartBadge()
      cy.Checkout()
      cy.Name().type('Juan')
      cy.Lastname().type('Diaz, Alguera')
      cy.PostalCode().type('1251')
      cy.Continue()
      cy.Finish()
     cy.wait(500)
     cy.center()
     cy.wait(1500)
     cy.backhome()
     cy.wait(600)
     cy.center()
    })
  })