describe('Buy Page', () => {
    it('successfully login and buy', () => {
      cy.login()
      cy.wait(500)
      cy.buybackpack()
      cy.wait(500)
      cy.ShoppingCartBadge()
      cy.wait(500)
      cy.Checkout()
      cy.wait(500)
      cy.get('[data-test="cancel"]').click()
      cy.wait(500)
      cy.scrollTo(200, 250)
      cy.wait(500)
      cy.get('[data-test="remove-sauce-labs-backpack"]').click()
      cy.wait(500)
      cy.get('[data-test="continue-shopping"]').click()
    })
  })